#!/usr/bin/env python3
"""Generate ``engine/src/blowfish_tables.h`` from the verified Python MIX reader.

The Blowfish P-array / S-boxes are the hexadecimal digits of pi.  They already
exist, verified, in ``maptools/mix_file.py`` (which in turn took them from the
bundled reference implementation ``data/_mix_tools/Blowfish.cs``).  Generating
the C++ header from that source rather than transcribing it by hand removes an
entire class of transcription error -- a single wrong nibble in an S-box would
produce a key schedule that silently decrypts to garbage.

The Westwood public modulus is also precomputed here: the vendor routine builds
it from a 56-byte base64 string with a bignum expansion, and baking the 64-byte
result into the header saves the C++ side from reimplementing that.

Usage::

    python3 tools/gen_blowfish_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from maptools.mix_file import (  # noqa: E402
    P_INIT,
    S_INIT,
    _PUBKEY_STR,
    _RSA_PUBLIC_EXPONENT,
    _public_modulus,
)

OUT = ROOT / "engine" / "src" / "blowfish_tables.h"


def main() -> int:
    p_init = list(P_INIT)
    s_init = [list(box) for box in S_INIT]

    if len(p_init) != 18:
        raise SystemExit(f"P_INIT must hold 18 words, got {len(p_init)}")
    if len(s_init) != 4 or any(len(box) != 256 for box in s_init):
        raise SystemExit("S_INIT must be four boxes of 256 words")
    for value in p_init + [w for box in s_init for w in box]:
        if not 0 <= value <= 0xFFFFFFFF:
            raise SystemExit(f"word out of range: {value!r}")

    modulus, pubkey_len = _public_modulus()
    if int(modulus).bit_length() - 1 != pubkey_len:
        raise SystemExit("public modulus length disagrees with init_pubkey")
    mod_bytes = int(modulus).to_bytes(64, "little")

    lines: list[str] = [
        "// GENERATED by tools/gen_blowfish_tables.py -- do not edit by hand.",
        "//",
        "// P-array and S-boxes are the hexadecimal digits of pi, taken from the",
        "// verified Python reader maptools/mix_file.py (itself extracted from the",
        "// bundled reference implementation data/_mix_tools/Blowfish.cs).",
        "// The 64-byte RSA modulus is precomputed there too.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace mg {",
        "",
        "inline constexpr std::uint32_t kPInit[18] = {",
    ]
    for i in range(0, 18, 6):
        lines.append("    " + ", ".join("0x%08Xu" % v for v in p_init[i : i + 6]) + ",")
    lines += ["};", "", "inline constexpr std::uint32_t kSInit[4][256] = {"]
    for box in s_init:
        lines.append("    {")
        for i in range(0, 256, 6):
            lines.append("        " + ", ".join("0x%08Xu" % v for v in box[i : i + 6]) + ",")
        lines.append("    },")
    lines += [
        "};",
        "",
        "// Westwood public key (BlowfishKeyProvider.cs): the 56-byte base64 string",
        "// expands to the 64-byte RSA modulus below.",
        'inline constexpr char kPublicKeyStr[] = "%s";' % _PUBKEY_STR,
        "inline constexpr std::uint32_t kRsaPublicExponent = 0x%Xu;" % _RSA_PUBLIC_EXPONENT,
        "",
        "inline constexpr std::uint8_t kPublicModulus[64] = {",
    ]
    for i in range(0, 64, 12):
        lines.append("    " + ", ".join("0x%02X" % b for b in mod_bytes[i : i + 12]) + ",")
    lines += ["};", "", "}  // namespace mg", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(lines)} lines)")
    print(f"  P-array 18 words, 4 S-boxes x 256 words, modulus {int(modulus).bit_length()} bits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
